name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ./app
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Build
        working-directory: ./app
        run: yarn build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Bootstrap Terraform
        shell: pwsh
        env:
          AWS_DEFAULT_REGION: ${{ secrets.TERRAFORM_AWS_REGION }}
        run: |
          .\build\bootstrap-terraform.ps1 `
            -StateBucketName '${{ secrets.TERRAFORM_STATE_BUCKET_NAME }}' `
            -LockStateTableName '${{ secrets.TERRAFORM_LOCK_STATE_TABLE_NAME }}' `
            -AwsRegion '${{ secrets.TERRAFORM_AWS_REGION }}'
      - run: terraform --version
      - name: Terraform Init
        run: >
          terraform init
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET_NAME }}"
            -backend-config="dynamodb_table=${{ secrets.TERRAFORM_LOCK_STATE_TABLE_NAME }}"
            -backend-config="region=${{ secrets.TERRAFORM_AWS_REGION }}"
            -input=false
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
